# Generated by Django 5.2 on 2025-07-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.CharField(default='https://tse4.mm.bing.net/th/id/OIP.5Uy16-H5NnlOh-XJjztaMwHaHa?pid=Api&P=0&h=180', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=10)),
                ('isVeg', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='delivery.restaurant')),
            ],
        ),
    ]
